fruits =['apple', 'banana', 'orange']
print(fruits)
print(fruits[1])
fruits.append("pineapple")
print(fruits)
fruits.append("kiwi")
print(fruits)
fruits.remove('banana')
print(fruits)
print(fruits.index('pineapple'))
fruits.reverse()
print(fruits)
fruits.sort()
print(fruits)
print(fruits.count("kiwi"))
fruits.clear()
print(fruits)
print('total fruits: ', len(fruits))